### ISSUE TITLE
Size seems to not be correct

### ISSUE THREAD

**Issue by midudev** [eihabkhan/terminal-big-sur-icons#1]
Using the icon seems to be bigger than expected.

![image](https://user-images.githubusercontent.com/1561955/99953840-26823d00-2d82-11eb-9b8d-5c63c12d387d.png)

**Comment by keemeleon** [comment]
I got the same issue with the Hyper icon.
<img width="200" alt="Screen Shot 2021-01-28 at 6 51 33 PM" src="https://user-images.githubusercontent.com/8077361/106216967-d9638280-6199-11eb-8521-10152e64838b.png">

**Comment by eihabkhan2** [comment]
> Using the icon seems to be bigger than expected.
> 
> ![image](https://user-images.githubusercontent.com/1561955/99953840-26823d00-2d82-11eb-9b8d-5c63c12d387d.png)

Thanks for bringing it up to my attention, I have removed iTerm as the app already supports Big Sur

**Comment by eihabkhan2** [comment]
> I got the same issue with the Hyper icon.
> <img alt="Screen Shot 2021-01-28 at 6 51 33 PM" width="200" src="https://user-images.githubusercontent.com/8077361/106216967-d9638280-6199-11eb-8521-10152e64838b.png">

Hyper still doesn't support Big Sur's theme, so I have modified it and fixed the size error. It should work fine now 👍
